# -*- coding: utf-8 -*-
"""project13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BodyLipuiYmTR3HO4uvEUgXa86fc4I6r
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

import plotly.express as px

df = pd.read_csv(
    "loan.csv.csv",
    nrows=50000
)

df = df[['loan_amnt',
         'term',
         'int_rate',
         'annual_inc',
         'emp_length',
         'home_ownership',
         'purpose',
         'grade',
         'loan_status']]

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET INFO")
print(df.info())

print("\nMISSING VALUES")
print(df.isnull().sum())

df.dropna(inplace=True)

df['term'] = df['term'].astype(str)


df['term'] = df['term'].str.replace(' months', '', regex=False)

df['term'] = df['term'].astype(int)


print(df['term'].head())

df['int_rate'] = df['int_rate'].astype(str)


df['int_rate'] = df['int_rate'].str.replace('%', '', regex=False)


df['int_rate'] = df['int_rate'].astype(float)

print(df['int_rate'].head())

def risk_category(rate):
    if rate < 10:
        return "Low Risk"
    elif rate < 20:
        return "Medium Risk"
    else:
        return "High Risk"

df['risk_level'] = df['int_rate'].apply(risk_category)

print("\nRISK LEVEL COUNTS")
print(df['risk_level'].value_counts())

plt.figure(figsize=(8,5))
sns.countplot(x='loan_status', data=df)
plt.xticks(rotation=90)
plt.title("Loan Status Distribution")
plt.show()


plt.figure(figsize=(8,5))
sns.histplot(df['annual_inc'], bins=30)
plt.title("Annual Income Distribution")
plt.show()


plt.figure(figsize=(8,5))
sns.histplot(df['loan_amnt'], bins=30)
plt.title("Loan Amount Distribution")
plt.show()


plt.figure(figsize=(8,5))
sns.scatterplot(x='int_rate', y='loan_amnt', data=df)
plt.title("Interest Rate vs Loan Amount")
plt.show()


plt.figure(figsize=(10,8))

numeric_df = df.select_dtypes(include=np.number)

sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

df_encoded = pd.get_dummies(
    df,
    columns=['home_ownership', 'purpose', 'grade'],
    drop_first=True
)

X = df_encoded[['annual_inc', 'int_rate', 'term']]


y = df_encoded['loan_amnt']


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = LinearRegression()


model.fit(X_train, y_train)


predictions = model.predict(X_test)

score = r2_score(y_test, predictions)

print("\nR2 SCORE")
print(score)


plt.figure(figsize=(8,5))

sns.scatterplot(x=y_test, y=predictions)

plt.xlabel("Actual Loan Amount")
plt.ylabel("Predicted Loan Amount")

plt.title("Actual vs Predicted")

plt.show()

fig = px.scatter(
    df,
    x='annual_inc',
    y='loan_amnt',
    color='risk_level',
    title='Income vs Loan Amount'
)

fig.show()

fig2 = px.histogram(
    df,
    x='loan_amnt',
    color='risk_level',
    title='Loan Amount Distribution'
)

fig2.show()

print("\nFINAL INSIGHTS")

print("1. Higher interest rates indicate higher risk borrowers.")
print("2. Borrowers with lower income may have higher default chances.")
print("3. Loan amount and interest rate show relationship.")
print("4. Risk levels help identify possible defaulters.")
print("5. Linear Regression predicts loan amount using financial factors.")

print("\nPROJECT COMPLETED SUCCESSFULLY")